x-environment: &dev_environment
  PYTHONUNBUFFERED: 1
  STAGE: "DEV"
  DEBUG: "True"
  DB_NAME: postgres
  DB_HOST: database
  DB_PASSWORD: postgres
  DB_PORT: 5432
  DB_USER: postgres
  DB_SSLMODE: disable

x-logging: &default_logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  smartrouter:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      <<: *dev_environment
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    logging: *default_logging

  database:
    image: postgres:16
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    logging: *default_logging


# volumes:
#   postgres_data:
