x-environment: &dev_environment
  PYTHONUNBUFFERED: 1
  STAGE: "DEV"
  DEBUG: "True"
  DB_NAME: postgres
  DB_HOST: db
  DB_PASSWORD: postgres
  DB_PORT: 5432
  DB_USER: postgres
  DB_SSLMODE: disable

x-logging: &default_logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  SmartRouter:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      <<: *dev_environment
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    logging: *default_logging

  Database:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging: *default_logging

  Nginx:
    image: nginx:stable
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    logging: *default_logging

volumes:
  postgres_data:
