# Generated by Django 5.2.4 on 2025-07-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_key_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_access_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
