# Generated by Django 5.2.4 on 2025-07-27 01:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('ssh_key', models.TextField(blank=True, help_text='SSH private key for authentication')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stopped', 'Stopped'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creating_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creating_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
