# Generated by Django 5.2.4 on 2025-07-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='aws_instance_id',
            field=models.CharField(blank=True, help_text='AWS EC2 instance ID (e.g., i-1234567890abcdef0)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='instance_type',
            field=models.CharField(choices=[('t2.nano', 't2.nano'), ('t2.micro', 't2.micro'), ('t2.small', 't2.small'), ('t2.medium', 't2.medium'), ('t2.large', 't2.large'), ('t3.nano', 't3.nano'), ('t3.micro', 't3.micro'), ('t3.small', 't3.small'), ('t3.medium', 't3.medium'), ('t3.large', 't3.large')], default='t2.micro', max_length=20),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='region',
            field=models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('ca-central-1', 'Canada (Central)'), ('eu-central-1', 'Europe (Frankfurt)'), ('eu-west-1', 'Europe (Ireland)'), ('eu-west-2', 'Europe (London)'), ('eu-west-3', 'Europe (Paris)'), ('eu-north-1', 'Europe (Stockholm)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('ap-northeast-2', 'Asia Pacific (Seoul)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('sa-east-1', 'South America (São Paulo)')], default='us-east-1', max_length=20),
        ),
    ]
