# Generated by Django 5.2.4 on 2025-08-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_ec2instance_aws_instance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='aws_instance_id',
            field=models.CharField(blank=True, help_text='AWS EC2 instance ID (e.g., i-1234567890abcdef0)', max_length=20, null=True, unique=True),
        ),
    ]
